/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Country;
import model.ModelMgr;

/**
 *
 * @author amir
 */
public class CountriesTable extends javax.swing.JPanel {

    /**
     * Creates new form CountriesTable
     */
    public CountriesTable() {
        initComponents();
        List<Country> countryList = ModelMgr.getInstance().getCountryList();
        combo_sort_year.setModel(ModelMgr.getInstance().getYearsComboModelForGrowth());
        combo_sort_year.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_sort_result = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        combo_sort_year = new javax.swing.JComboBox();

        setMaximumSize(new java.awt.Dimension(576, 360));
        setPreferredSize(new java.awt.Dimension(576, 360));

        table_sort_result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Country" , "Pupulation"
            }
        ));
        jScrollPane1.setViewportView(table_sort_result);

        jLabel1.setText("Choose Year:");

        combo_sort_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        combo_sort_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_sort_yearActionPerformed(evt);
            }
        });
        combo_sort_year.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                combo_sort_yearVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(combo_sort_year, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo_sort_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_sort_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_sort_yearActionPerformed
        // TODO add your handling code here:
        if(combo_sort_year.getSelectedIndex() == -1){
            return;
        }
        
        int year = Integer.parseInt(combo_sort_year.getSelectedItem().toString());
        int index = 0;
        List<Country> countryList = ModelMgr.getInstance().getCountryList();
        System.out.println(countryList.size());
        for(int i=0;i<countryList.get(0).growths.size();i++){
            if(countryList.get(0).growths.get(i).startYear == year){
                index = i;
                break;
            }
        }
        final int choose = index;
        Collections.sort(countryList, new Comparator<Country>() {
                @Override
                public int compare(Country o1, Country o2) {
                    if(o1.growths.size() <= choose && o2.growths.size() <= choose)
                        return 0;
                    if(o1.growths.size() <= choose)
                        return -1;
                    if(o2.growths.size() <= choose)
                        return 1;
                    return Double.compare(o2.growths.get(choose).growth, o1.growths.get(choose).growth);
                }
            });
        DefaultTableModel model = (DefaultTableModel)table_sort_result.getModel();
        model.setRowCount(0);
        for(Country country: countryList){
            if(country.growths.size()>choose)
                model.addRow(new Object[]{country.countryName, country.growths.get(choose).growth});
        }

    }//GEN-LAST:event_combo_sort_yearActionPerformed

    
    private void combo_sort_yearVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_combo_sort_yearVetoableChange
        // TODO add your handling code here:

    }//GEN-LAST:event_combo_sort_yearVetoableChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_sort_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_sort_result;
    // End of variables declaration//GEN-END:variables
}
